### User Signup
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "John Doe",
  "email": "user@example.com",
  "password": "123456"
}

### User Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

### Admin Signup
POST http://localhost:3000/adminSignup
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@example.com",
  "password": "123456",
  "secret": "BekiJunior"
}

### Get Users (Admin only)
GET http://localhost:3000/getusers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWVjOTEyYmJhNWJmYmNjYWM4OGQ5MjciLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzcxMTEzOTgsImV4cCI6MTc3NzExNDk5OH0.kCIsieFesUQISGt2wm2tVrD_DsF33tH_fPchO2G4bDM

### Send Message (User only)
POST http://localhost:3000/message
Content-Type: application/json
Authorization: Bearer YOUR_USER_TOKEN

{
  "name": "Beki",
  "email": "beki@example.com",
  "message": "Hello, this is a test message"
}

### Get Messages (Admin only)
GET http://localhost:3000/getMessages
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWVjOTEyYmJhNWJmYmNjYWM4OGQ5MjciLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzcxMTMxODYsImV4cCI6MTc3NzExNjc4Nn0.j4R1SSBImPZ1NG4QhrFzWbFAKoyetwWneavG8IswBgg